"""Traceable material-specific parameter records."""

from .pentacene import (
    DEWIJS_2003_HOMO_ONSITE_DIFFERENCE_EV,
    DEWIJS_2003_HOMO_SIGNED_HOPPINGS_EV,
    DEWIJS_2003_SOURCE_DOI,
    NEEF_2024_ARPES_HOLE_HOPPINGS,
    NEEF_2024_MD_HOLE_HOPPING_STATISTICS,
    NEEF_2024_MD_TEMPERATURE_K,
    NEEF_2024_MEAN_TRANSLATIONAL_FLUCTUATION_ANGSTROM,
    NEEF_2024_PEER_REVIEWED,
    NEEF_2024_SOURCE_DOI,
    PENTACENE_293K,
    PENTACENE_293K_CROSS_SOURCE_HOLE_HOPPINGS_EV,
    PENTACENE_293K_CROSS_SOURCE_STATUS,
    PENTACENE_90K,
    STEHR_2011_HOLE_COUPLINGS,
    UNRESOLVED_PENTACENE_FIELDS,
    pentacene_293k_candidate_transport_lattice,
    pentacene_293k_cross_source_hole_model,
    pentacene_293k_projected_lattice,
    pentacene_90k_dewijs_homo_model,
    pentacene_90k_dewijs_reference_lattice,
    pentacene_room_temperature_neef_arpes_homo_model,
)
from .pentacene_atomistic import (
    MATT_HEUS_2001_293K_CCDC as MATTHEUS_2001_293K_CCDC,
    MATT_HEUS_2001_CIF_PATH as MATTHEUS_2001_CIF_PATH,
    MATT_HEUS_2001_COORDINATE_STATUS as MATTHEUS_2001_COORDINATE_STATUS,
    MATT_HEUS_2001_SOURCE_DOI as MATTHEUS_2001_SOURCE_DOI,
    PENTACENE_293K_ATOMISTIC_DIMER_FAMILIES,
    PENTACENE_293K_CELL_3D,
    AtomisticPentaceneDimer,
    AtomisticPentaceneMolecule,
    TriclinicCell3D,
    pentacene_293k_atomistic_basis_a,
    pentacene_293k_atomistic_basis_b,
    pentacene_293k_atomistic_dimer,
    pentacene_293k_atomistic_dimer_set,
)
from .pentacene_epc import (
    GNOLI_2025_DATASET_DOI,
    GNOLI_2025_EPC_FINITE_DISPLACEMENT_ANGSTROM,
    GNOLI_2025_LT_DOMINANT_EPC,
    GNOLI_2025_REPRESENTATION,
    GNOLI_2025_SOURCE_DOI,
    ModalEpcEvidence,
    g5d_projection_requirements,
)
from .pentacene_g5e import (
    NEEF_2024_FODFT_PROTOCOL,
    PENTACENE_G5E_G3_MODE_UNITS,
    PENTACENE_G5E_ORIENTED_BOND_FAMILIES,
    PENTACENE_G5E_ROTATION_STEPS_DEGREE,
    PENTACENE_G5E_TRANSLATION_STEPS_ANGSTROM,
    FoDftReferenceProtocol,
    pentacene_g5e_displaced_calculation_count_per_oriented_bond,
    pentacene_g5e_full_oriented_scan_calculation_count,
    pentacene_g5e_promotion_requirements,
    pentacene_g5e_scan_plan,
)

__all__ = [
    "AtomisticPentaceneDimer",
    "AtomisticPentaceneMolecule",
    "DEWIJS_2003_HOMO_ONSITE_DIFFERENCE_EV",
    "DEWIJS_2003_HOMO_SIGNED_HOPPINGS_EV",
    "DEWIJS_2003_SOURCE_DOI",
    "FoDftReferenceProtocol",
    "GNOLI_2025_DATASET_DOI",
    "GNOLI_2025_EPC_FINITE_DISPLACEMENT_ANGSTROM",
    "GNOLI_2025_LT_DOMINANT_EPC",
    "GNOLI_2025_REPRESENTATION",
    "GNOLI_2025_SOURCE_DOI",
    "MATTHEUS_2001_293K_CCDC",
    "MATTHEUS_2001_CIF_PATH",
    "MATTHEUS_2001_COORDINATE_STATUS",
    "MATTHEUS_2001_SOURCE_DOI",
    "ModalEpcEvidence",
    "NEEF_2024_ARPES_HOLE_HOPPINGS",
    "NEEF_2024_FODFT_PROTOCOL",
    "NEEF_2024_MD_HOLE_HOPPING_STATISTICS",
    "NEEF_2024_MD_TEMPERATURE_K",
    "NEEF_2024_MEAN_TRANSLATIONAL_FLUCTUATION_ANGSTROM",
    "NEEF_2024_PEER_REVIEWED",
    "NEEF_2024_SOURCE_DOI",
    "PENTACENE_293K",
    "PENTACENE_293K_ATOMISTIC_DIMER_FAMILIES",
    "PENTACENE_293K_CELL_3D",
    "PENTACENE_293K_CROSS_SOURCE_HOLE_HOPPINGS_EV",
    "PENTACENE_293K_CROSS_SOURCE_STATUS",
    "PENTACENE_90K",
    "PENTACENE_G5E_G3_MODE_UNITS",
    "PENTACENE_G5E_ORIENTED_BOND_FAMILIES",
    "PENTACENE_G5E_ROTATION_STEPS_DEGREE",
    "PENTACENE_G5E_TRANSLATION_STEPS_ANGSTROM",
    "STEHR_2011_HOLE_COUPLINGS",
    "TriclinicCell3D",
    "UNRESOLVED_PENTACENE_FIELDS",
    "g5d_projection_requirements",
    "pentacene_293k_atomistic_basis_a",
    "pentacene_293k_atomistic_basis_b",
    "pentacene_293k_atomistic_dimer",
    "pentacene_293k_atomistic_dimer_set",
    "pentacene_293k_candidate_transport_lattice",
    "pentacene_293k_cross_source_hole_model",
    "pentacene_293k_projected_lattice",
    "pentacene_90k_dewijs_homo_model",
    "pentacene_90k_dewijs_reference_lattice",
    "pentacene_g5e_displaced_calculation_count_per_oriented_bond",
    "pentacene_g5e_full_oriented_scan_calculation_count",
    "pentacene_g5e_promotion_requirements",
    "pentacene_g5e_scan_plan",
    "pentacene_room_temperature_neef_arpes_homo_model",
]
