"""Safe rendering helpers for the documented FHI-aims H2n@DA FO-DFT workflow.

G5f is intentionally narrower than a general FHI-aims input generator.  It
renders only the fragment-orbital DFT keywords and molecular geometries whose
syntax is explicitly documented in the current FHI-aims manual.  Exchange-
correlation, species defaults, basis files, SCF settings, executable paths, and
scheduler configuration remain external inputs.

The adapter targets the classic H2n@DA scheme used as the G5e pentacene
reference: neutral fragment calculations, ``fo_flavour default``, followed by a
final combined-system calculation.  ``fo_deltaplus`` is deliberately excluded.
"""

from __future__ import annotations

from dataclasses import dataclass
import re

import numpy as np

from .dimer_finite_difference import (
    DimerPerturbation,
    RigidDimerReference,
    RigidMoleculeGeometry,
)

_SAFE_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")


def _validate_folder_name(name: str) -> None:
    if not _SAFE_NAME.fullmatch(name):
        raise ValueError(
            "folder names must contain only letters, digits, underscore, dot, and hyphen"
        )
    if name in {".", ".."}:
        raise ValueError("folder names must not be '.' or '..'")


def _format_float(value: float) -> str:
    if not np.isfinite(value):
        raise ValueError("geometry coordinates must be finite")
    return f"{float(value):.12f}"


def render_molecule_geometry_in(molecule: RigidMoleculeGeometry) -> str:
    """Render one isolated molecular fragment in FHI-aims ``geometry.in`` syntax."""
    lines = ["# generated by holstein-peierls-transport G5f"]
    for symbol, coordinate in zip(molecule.symbols, molecule.coordinates):
        if not symbol or any(character.isspace() for character in symbol):
            raise ValueError("atomic species labels must be non-empty and whitespace-free")
        x, y, z = (_format_float(value) for value in coordinate)
        lines.append(f"atom {x} {y} {z} {symbol}")
    return "\n".join(lines) + "\n"


def render_dimer_geometry_in(reference: RigidDimerReference) -> str:
    """Render the combined dimer with fragment A atoms followed by fragment B atoms.

    The current FHI-aims manual requires the dimer atom ordering to mirror the
    actual fragmentation.  This renderer therefore never interleaves fragments.
    """
    lines = [
        "# generated by holstein-peierls-transport G5f",
        "# fragment 1 / molecule A",
    ]
    for symbol, coordinate in zip(
        reference.molecule_a.symbols, reference.molecule_a.coordinates
    ):
        x, y, z = (_format_float(value) for value in coordinate)
        lines.append(f"atom {x} {y} {z} {symbol}")
    lines.append("# fragment 2 / molecule B")
    for symbol, coordinate in zip(
        reference.molecule_b.symbols, reference.molecule_b.coordinates
    ):
        x, y, z = (_format_float(value) for value in coordinate)
        lines.append(f"atom {x} {y} {z} {symbol}")
    return "\n".join(lines) + "\n"


def render_fragment_fodft_control_block() -> str:
    """Render the documented neutral-fragment H2n@DA FO-DFT block."""
    return "fo_dft fragment\nfo_flavour default\n"


@dataclass(frozen=True, slots=True)
class FinalFodftSelection:
    """Selected isolated-fragment states for one final hole-coupling calculation."""

    state_fragment_1: int
    state_fragment_2: int
    range_fragment_1: int = 1
    range_fragment_2: int = 1
    transport_type: str = "hole"
    verbosity: int = 1

    def __post_init__(self) -> None:
        for name, value in (
            ("state_fragment_1", self.state_fragment_1),
            ("state_fragment_2", self.state_fragment_2),
            ("range_fragment_1", self.range_fragment_1),
            ("range_fragment_2", self.range_fragment_2),
        ):
            if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
                raise ValueError(f"{name} must be a positive integer")
        if self.transport_type not in {"hole", "dn", "elec", "up"}:
            raise ValueError("transport_type must be one of hole, dn, elec, or up")
        if self.verbosity not in {0, 1, 2}:
            raise ValueError("verbosity must be 0, 1, or 2")


def render_final_fodft_control_block(
    selection: FinalFodftSelection,
    *,
    fragment_1_folder: str = "frag1",
    fragment_2_folder: str = "frag2",
) -> str:
    """Render only the documented FO-DFT tags for the final combined calculation."""
    _validate_folder_name(fragment_1_folder)
    _validate_folder_name(fragment_2_folder)
    if fragment_1_folder == fragment_2_folder:
        raise ValueError("fragment folders must be distinct")
    return (
        "fo_dft final\n"
        "fo_flavour default\n"
        f"fo_folders {fragment_1_folder} {fragment_2_folder}\n"
        f"fo_orbitals {selection.state_fragment_1} {selection.state_fragment_2} "
        f"{selection.range_fragment_1} {selection.range_fragment_2} "
        f"{selection.transport_type}\n"
        f"fo_verbosity {selection.verbosity}\n"
    )


def sanitize_job_component(value: str) -> str:
    """Return one deterministic path-safe component for a scan job."""
    normalized = re.sub(r"[^A-Za-z0-9_.-]+", "-", value.strip())
    normalized = normalized.strip(".-")
    if not normalized:
        raise ValueError("job component must contain at least one safe character")
    return normalized


def perturbation_job_tag(family_label: str, perturbation: DimerPerturbation) -> str:
    """Return a stable folder tag for one bond/coordinate/sign/step combination."""
    family = sanitize_job_component(family_label)
    coordinate = sanitize_job_component(perturbation.coordinate_label)
    sign = "plus" if perturbation.amount > 0.0 else "minus"
    magnitude = f"{abs(float(perturbation.amount)):.12g}".replace("+", "p")
    magnitude = magnitude.replace("-", "m").replace(".", "p")
    unit = "A" if perturbation.unit == "angstrom" else "rad"
    return f"{family}__{coordinate}__{sign}__{magnitude}{unit}"


@dataclass(frozen=True, slots=True)
class FodftJobLayout:
    """Three-calculation sibling-folder layout required for one FODFT coupling."""

    root_name: str
    fragment_1_folder: str = "frag1"
    fragment_2_folder: str = "frag2"
    final_folder: str = "dimer"

    def __post_init__(self) -> None:
        for value in (
            self.root_name,
            self.fragment_1_folder,
            self.fragment_2_folder,
            self.final_folder,
        ):
            _validate_folder_name(value)
        if len(
            {self.fragment_1_folder, self.fragment_2_folder, self.final_folder}
        ) != 3:
            raise ValueError("fragment and final calculation folders must be distinct")

    @property
    def calculation_count(self) -> int:
        return 3


@dataclass(frozen=True, slots=True)
class FodftInputBundle:
    """Rendered FO-DFT-specific content for one signed transfer-integral evaluation."""

    layout: FodftJobLayout
    fragment_1_geometry_in: str
    fragment_2_geometry_in: str
    dimer_geometry_in: str
    fragment_control_block: str
    final_control_block: str

    def file_map(self) -> dict[str, str]:
        """Return relative paths to text fragments that should be materialized by a runner."""
        root = self.layout.root_name
        return {
            f"{root}/{self.layout.fragment_1_folder}/geometry.in": self.fragment_1_geometry_in,
            f"{root}/{self.layout.fragment_1_folder}/fodft.control": self.fragment_control_block,
            f"{root}/{self.layout.fragment_2_folder}/geometry.in": self.fragment_2_geometry_in,
            f"{root}/{self.layout.fragment_2_folder}/fodft.control": self.fragment_control_block,
            f"{root}/{self.layout.final_folder}/geometry.in": self.dimer_geometry_in,
            f"{root}/{self.layout.final_folder}/fodft.control": self.final_control_block,
        }


def build_fodft_input_bundle(
    reference: RigidDimerReference,
    selection: FinalFodftSelection,
    *,
    root_name: str,
) -> FodftInputBundle:
    """Build the documented FO-DFT pieces without inventing a full ``control.in``."""
    layout = FodftJobLayout(root_name=root_name)
    return FodftInputBundle(
        layout=layout,
        fragment_1_geometry_in=render_molecule_geometry_in(reference.molecule_a),
        fragment_2_geometry_in=render_molecule_geometry_in(reference.molecule_b),
        dimer_geometry_in=render_dimer_geometry_in(reference),
        fragment_control_block=render_fragment_fodft_control_block(),
        final_control_block=render_final_fodft_control_block(
            selection,
            fragment_1_folder=layout.fragment_1_folder,
            fragment_2_folder=layout.fragment_2_folder,
        ),
    )


def g5f_output_parser_status() -> tuple[str, str]:
    """Document why a transfer-integral output parser is not yet part of G5f."""
    return (
        "deferred",
        "the official manual documents the full_hab_submatrix filename but not its exact text format",
    )
