"""Material-agnostic two-dimensional periodic molecular-lattice geometry.

This module is intentionally independent of the validated Holstein-Peierls
solvers. It provides only immutable crystal geometry, periodic site indexing,
bond-graph generation, physical coordinates, and minimum-image distances. The
existing rectangular solver remains the reference implementation during the G1
migration stage.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from itertools import product

import numpy as np
from numpy.typing import NDArray

FloatArray = NDArray[np.float64]


@dataclass(frozen=True, slots=True)
class MolecularBasisSite:
    """One molecule in the primitive-cell basis.

    ``position_fractional`` contains coefficients along the primitive Bravais
    vectors ``a1`` and ``a2``. Values outside ``[0, 1)`` are allowed because
    they can be useful when importing crystallographic models; periodic
    equivalence is handled by the lattice rather than by silently rewriting the
    supplied coordinates.
    """

    label: str
    position_fractional: tuple[float, float]

    def __post_init__(self) -> None:
        if not self.label.strip():
            raise ValueError("basis-site label must be non-empty")
        position = np.asarray(self.position_fractional, dtype=np.float64)
        if position.shape != (2,) or not np.all(np.isfinite(position)):
            raise ValueError("basis position_fractional must contain two finite values")


@dataclass(frozen=True, slots=True)
class BondFamily:
    """One translationally repeated undirected molecular contact family.

    ``cell_offset = (delta_n1, delta_n2)`` translates the target primitive cell
    along ``a1`` and ``a2``, respectively. Only one orientation of an
    undirected family should be supplied; reverse hopping is generated by the
    future Hamiltonian builder rather than stored as a second family.
    """

    label: str
    source_basis: int
    target_basis: int
    cell_offset: tuple[int, int]

    def __post_init__(self) -> None:
        if not self.label.strip():
            raise ValueError("bond-family label must be non-empty")
        if len(self.cell_offset) != 2 or not all(
            isinstance(value, (int, np.integer)) for value in self.cell_offset
        ):
            raise ValueError("bond-family cell_offset must contain two integers")
        if self.source_basis < 0 or self.target_basis < 0:
            raise ValueError("bond-family basis indices must be non-negative")
        if self.source_basis == self.target_basis and self.cell_offset == (0, 0):
            raise ValueError("a bond family cannot connect a site to itself")


@dataclass(frozen=True, slots=True)
class MolecularBond:
    """One generated undirected edge plus its bond-family orientation."""

    family: str
    source: int
    target: int
    family_source: int
    family_target: int


@dataclass(frozen=True, slots=True)
class PeriodicMolecularLattice2D:
    """Immutable 2D periodic molecular crystal with an arbitrary basis."""

    n1: int
    n2: int
    a1_angstrom: tuple[float, float]
    a2_angstrom: tuple[float, float]
    basis: tuple[MolecularBasisSite, ...]
    bonds: tuple[BondFamily, ...] = ()
    _legacy_rectangular_spacings: tuple[float, float] | None = field(
        default=None, repr=False, compare=False
    )

    def __post_init__(self) -> None:
        if self.n1 <= 0 or self.n2 <= 0:
            raise ValueError("n1 and n2 must be positive")
        if not self.basis:
            raise ValueError("the molecular basis must contain at least one site")

        a1 = np.asarray(self.a1_angstrom, dtype=np.float64)
        a2 = np.asarray(self.a2_angstrom, dtype=np.float64)
        if a1.shape != (2,) or a2.shape != (2,):
            raise ValueError("a1_angstrom and a2_angstrom must be 2D vectors")
        if not np.all(np.isfinite(a1)) or not np.all(np.isfinite(a2)):
            raise ValueError("Bravais vectors must contain finite values")
        determinant = float(np.linalg.det(np.column_stack((a1, a2))))
        scale = max(float(np.linalg.norm(a1) * np.linalg.norm(a2)), 1.0)
        if abs(determinant) <= 1.0e-12 * scale:
            raise ValueError("Bravais vectors must be linearly independent")

        basis_labels = [site.label for site in self.basis]
        if len(set(basis_labels)) != len(basis_labels):
            raise ValueError("basis-site labels must be unique")

        bond_labels = [bond.label for bond in self.bonds]
        if len(set(bond_labels)) != len(bond_labels):
            raise ValueError("bond-family labels must be unique")
        for bond in self.bonds:
            if bond.source_basis >= self.n_basis or bond.target_basis >= self.n_basis:
                raise ValueError(
                    f"bond family {bond.label!r} references a basis index outside "
                    f"0..{self.n_basis - 1}"
                )

        if self._legacy_rectangular_spacings is not None:
            sx, sy = self._legacy_rectangular_spacings
            if sx <= 0.0 or sy <= 0.0:
                raise ValueError("legacy rectangular spacings must be positive")
            if self.n_basis != 1 or self.basis[0].position_fractional != (0.0, 0.0):
                raise ValueError(
                    "legacy rectangular distance compatibility requires one basis "
                    "site at fractional position (0, 0)"
                )
            if self.a1_angstrom != (float(sx), 0.0) or self.a2_angstrom != (0.0, float(sy)):
                raise ValueError(
                    "legacy rectangular distance compatibility requires axis-aligned "
                    "Bravais vectors matching the supplied spacings"
                )

    @property
    def n_basis(self) -> int:
        return len(self.basis)

    @property
    def n_sites(self) -> int:
        return self.n1 * self.n2 * self.n_basis

    @property
    def bravais_matrix(self) -> FloatArray:
        """Return ``[a1 a2]`` with Bravais vectors stored as columns."""
        return np.column_stack(
            (
                np.asarray(self.a1_angstrom, dtype=np.float64),
                np.asarray(self.a2_angstrom, dtype=np.float64),
            )
        )

    @property
    def supercell_matrix(self) -> FloatArray:
        """Return finite-supercell vectors ``[n1*a1, n2*a2]`` as columns."""
        matrix = self.bravais_matrix.copy()
        matrix[:, 0] *= self.n1
        matrix[:, 1] *= self.n2
        return matrix

    def site_index(self, cell_y: int, cell_x: int, basis: int) -> int:
        """Map ``(cell_y, cell_x, basis)`` to the deterministic flat site index."""
        if not 0 <= cell_y < self.n2:
            raise IndexError("cell_y is outside the finite lattice")
        if not 0 <= cell_x < self.n1:
            raise IndexError("cell_x is outside the finite lattice")
        if not 0 <= basis < self.n_basis:
            raise IndexError("basis index is outside the molecular basis")
        return (cell_y * self.n1 + cell_x) * self.n_basis + basis

    def site_coordinates(self, index: int) -> tuple[int, int, int]:
        """Inverse of :meth:`site_index`, returning ``(cell_y, cell_x, basis)``."""
        if not 0 <= index < self.n_sites:
            raise IndexError("site index is outside the finite lattice")
        cell_flat, basis = divmod(index, self.n_basis)
        cell_y, cell_x = divmod(cell_flat, self.n1)
        return cell_y, cell_x, basis

    def basis_offsets_angstrom(self) -> FloatArray:
        """Return Cartesian basis offsets ``tau_s`` in angstrom."""
        fractional = np.asarray(
            [site.position_fractional for site in self.basis], dtype=np.float64
        )
        return fractional @ self.bravais_matrix.T

    def physical_positions_angstrom(self) -> FloatArray:
        """Return Cartesian molecular reference positions ordered by site index."""
        offsets = self.basis_offsets_angstrom()
        a1 = np.asarray(self.a1_angstrom, dtype=np.float64)
        a2 = np.asarray(self.a2_angstrom, dtype=np.float64)
        positions = np.empty((self.n_sites, 2), dtype=np.float64)
        for cell_y in range(self.n2):
            for cell_x in range(self.n1):
                cell_origin = cell_x * a1 + cell_y * a2
                for basis_index in range(self.n_basis):
                    index = self.site_index(cell_y, cell_x, basis_index)
                    positions[index] = cell_origin + offsets[basis_index]
        return positions

    def generated_bonds(self) -> tuple[MolecularBond, ...]:
        """Generate deterministic unique undirected bonds for the finite cell.

        ``source`` and ``target`` store the canonical undirected edge. The
        separate ``family_source`` and ``family_target`` fields preserve the
        orientation declared by the bond family, which is required for Peierls
        differences such as ``q_j - q_i``.

        Small periodic cells can map two translated representatives of the same
        family onto the same undirected edge. Such same-family duplicates are
        collapsed. If two *different* families map to the same edge, the model
        is ambiguous and a ``ValueError`` is raised rather than silently choosing
        one label.
        """
        generated: list[MolecularBond] = []
        edge_family: dict[tuple[int, int], str] = {}
        for family in self.bonds:
            delta_x, delta_y = family.cell_offset
            for cell_y in range(self.n2):
                for cell_x in range(self.n1):
                    source = self.site_index(cell_y, cell_x, family.source_basis)
                    target_x = (cell_x + delta_x) % self.n1
                    target_y = (cell_y + delta_y) % self.n2
                    target = self.site_index(target_y, target_x, family.target_basis)
                    if source == target:
                        raise ValueError(
                            f"bond family {family.label!r} collapses to a self-edge "
                            "in this finite supercell"
                        )
                    edge = (min(source, target), max(source, target))
                    previous = edge_family.get(edge)
                    if previous is None:
                        edge_family[edge] = family.label
                        generated.append(
                            MolecularBond(
                                family=family.label,
                                source=edge[0],
                                target=edge[1],
                                family_source=source,
                                family_target=target,
                            )
                        )
                    elif previous != family.label:
                        raise ValueError(
                            f"bond families {previous!r} and {family.label!r} generate "
                            f"the same undirected edge {edge}"
                        )
        return tuple(generated)

    @staticmethod
    def _minimum_image_from_raw_displacement(
        displacement: FloatArray,
        supercell: FloatArray,
    ) -> FloatArray:
        """Minimize one raw displacement over nearby supercell translations."""
        fractional = np.linalg.solve(supercell, displacement)
        nearest = np.rint(fractional).astype(np.int64)

        best: FloatArray | None = None
        best_norm2 = np.inf
        for offset_x, offset_y in product((-1, 0, 1), repeat=2):
            image = nearest + np.array((offset_x, offset_y), dtype=np.int64)
            candidate = displacement - supercell @ image
            norm2 = float(np.dot(candidate, candidate))
            if norm2 < best_norm2:
                best_norm2 = norm2
                best = candidate
        assert best is not None
        return np.asarray(best, dtype=np.float64)

    def minimum_image_displacement_angstrom(self, source: int, target: int) -> FloatArray:
        """Return the shortest periodic displacement from ``source`` to ``target``.

        For a non-orthogonal supercell the component-wise Cartesian wrapping used
        by a rectangular lattice is invalid. We transform the raw displacement
        to supercell fractional coordinates, round to the nearest lattice image,
        and explicitly inspect the surrounding 3x3 translation candidates, as
        prescribed by the G1 design.
        """
        if not 0 <= source < self.n_sites or not 0 <= target < self.n_sites:
            raise IndexError("site index is outside the finite lattice")
        if source == target:
            return np.zeros(2, dtype=np.float64)

        positions = self.physical_positions_angstrom()
        displacement = positions[target] - positions[source]
        return self._minimum_image_from_raw_displacement(
            displacement, self.supercell_matrix
        )

    def minimum_image_distances_angstrom(self) -> FloatArray:
        """Return the symmetric physical minimum-image pair-distance matrix.

        The compatibility lattice returned by :func:`rectangular_legacy_lattice`
        deliberately executes the *same floating-point operations* as the
        ``v0.6.0a1`` rectangular Coulomb helper. This preserves bitwise distance
        equality for the legacy geometry while general cells use the metric-aware
        image search above.
        """
        if self._legacy_rectangular_spacings is not None:
            spacing_x, spacing_y = self._legacy_rectangular_spacings
            indices = np.arange(self.n1 * self.n2, dtype=np.int64)
            y = indices // self.n1
            x = indices % self.n1
            dx_raw = np.abs(x[:, None] - x[None, :])
            dy_raw = np.abs(y[:, None] - y[None, :])
            dx = np.minimum(dx_raw, self.n1 - dx_raw).astype(np.int64)
            dy = np.minimum(dy_raw, self.n2 - dy_raw).astype(np.int64)
            rx = dx.astype(np.float64) * spacing_x
            ry = dy.astype(np.float64) * spacing_y
            return np.sqrt(np.square(rx) + np.square(ry))

        positions = self.physical_positions_angstrom()
        supercell = self.supercell_matrix
        distance = np.zeros((self.n_sites, self.n_sites), dtype=np.float64)
        for source in range(self.n_sites):
            for target in range(source + 1, self.n_sites):
                raw = positions[target] - positions[source]
                displacement = self._minimum_image_from_raw_displacement(raw, supercell)
                value = float(np.linalg.norm(displacement))
                distance[source, target] = value
                distance[target, source] = value
        return distance


def rectangular_legacy_lattice(
    nx: int,
    ny: int,
    spacing_x_angstrom: float,
    spacing_y_angstrom: float,
) -> PeriodicMolecularLattice2D:
    """Return the one-basis rectangular geometry of the validated legacy model.

    The site ordering and distance-matrix arithmetic intentionally match
    ``v0.6.0a1``. This adapter is the regression bridge; general crystal models
    should instantiate :class:`PeriodicMolecularLattice2D` directly.
    """
    if spacing_x_angstrom <= 0.0 or spacing_y_angstrom <= 0.0:
        raise ValueError("rectangular lattice spacings must be positive")
    sx = float(spacing_x_angstrom)
    sy = float(spacing_y_angstrom)
    return PeriodicMolecularLattice2D(
        n1=nx,
        n2=ny,
        a1_angstrom=(sx, 0.0),
        a2_angstrom=(0.0, sy),
        basis=(MolecularBasisSite("A", (0.0, 0.0)),),
        bonds=(
            BondFamily("x", 0, 0, (1, 0)),
            BondFamily("y", 0, 0, (0, 1)),
        ),
        _legacy_rectangular_spacings=(sx, sy),
    )
